# 1) First example
#FROM ubuntu:latest
#LABEL authors="Dell"
#
#ENTRYPOINT ["top", "-b"]

# Generated by chat gtp
# Use an official OpenJDK runtime as a parent image
#FROM openjdk:17-jdk-slim
#
## Set the working directory inside the container
#WORKDIR /app
#
## Copy the application jar file to the container
#COPY target/your-application.jar /app/application.jar
#
## Expose the port the app runs on
#EXPOSE 5000
#
## Run the application
#CMD ["java", "-jar", "/app/application.jar"]

# 2) Second example
##FROM openjdk:17-jdk-alpine
#FROM openjdk:17-jdk-slim
#ARG JAR_FILE=target/*.jar
#COPY ./target/polls-0.0.1-SNAPSHOT.jar app.jar
#EXPOSE 5000
#ENTRYPOINT ["java", "-jar", "/app.jar"]

# 3) Third example
#FROM ubuntu:latest AS build
#
#RUN apt-get update
#RUN apt-get install openjdk-17-jdk -y
#COPY . .
#
## RUN  ./gradlew bootJar --no-daemon
#RUN  ./mvnw bootJar --no-daemon
#
#FROM openjdk:17-jdk-slim
#
#EXPOSE 5000
#
##COPY --from=build /build/libs/demo-1.jar app.jar
#COPY --from=build /target/polls-0.0.1-SNAPSHOT.jar app.jar
#
#ENTRYPOINT ["java", "-jar", "app.jar"]

# 4) Fourth example
# FROM eclipse-temurin:17
#
# WORKDIR /app
#
# COPY target/polls-0.0.1-SNAPSHOT.jar /app/springboot-docker-demo.jar
#
# ENTRYPOINT ["java", "-jar", "springboot-docker-demo.jar"]

#
# Build stage
#
FROM maven:3.8.2-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

#
# Package stage
#
FROM openjdk:17-jdk-slim
COPY --from=build /target/polls-0.0.1-SNAPSHOT.jar polls.jar
EXPOSE 5000
ENTRYPOINT ["java","-jar","polls.jar"]
